<?php
declare(strict_types=1);

$lang  = isset($_GET['lang']) ? $_GET['lang'] : 'fr';
$title = "Carte Interactive - Point Météo";
$description = "la carte interactive des region de la france, elle permet à l'utilisateur de rechercher sa region, puis son departement pour enfin trouver sa ville.";

require "includes/header.inc.php";
require "includes/function.inc.php";  
require "includes/weather_api.php";

// Récupérer les départements, régions et villes 
$regions = get_departments();
// Les régions pour la map 
$mapRegions = array_keys($regions);

// Récupération des sélections 
$selectedRegion = isset($_GET['region']) ? $_GET['region'] : '';
$selectedDept   = isset($_GET['departement']) ? $_GET['departement'] : '';

?>



<main>
  <section class="container main-content">
    <h1><?= $lang === 'fr' ? 'Point Météo' : 'Point Météo' ?></h1>
    <div class="row">
      
      <!-- Image Map Generated by http://www.image-map.net/ -->
        <map name="france-map">
          <?php foreach ($mapRegions as $region): ?>
          <area
            shape="poly"
            coords="<?= get_region_coords($region) ?>"
            href="?region=<?=urlencode($region) ?>&lang=<?= $lang ?>"
            alt="<?= htmlspecialchars($region) ?>"
            title="<?= htmlspecialchars($region) ?>">
          <?php endforeach; ?>
        </map>
        <img usemap="#france-map" src="image/carte-france-regions.png" width="760" height="698" alt="Carte de France" class="img-fluid">

      <!-- FORMULAIRES-->
      <div class="col-md-4">
        <h2><?= $lang === 'fr' ? 'Sélectionnez votre localisation' : 'Select your location' ?></h2>

        <!-- On Sélectionne le département, si on a déjà la région -->
        <?php if ($selectedRegion && !$selectedDept): ?>
        <article id="department">
          <h3><?= $lang === 'fr' ? 'Renseignement du département' : 'Department information' ?></h3>
          <p>
            <?= $lang === 'fr' ? 'Région sélectionnée' : 'Selected region' ?> :
            <strong><?= $selectedRegion?></strong>
          </p>
          <form action="?lang=<?=$lang?>#department" method="get">
             <input type="hidden" name="region" value="<?=$selectedRegion?>">
                <label for="departement">
                    <?= $lang === 'fr' ? 'Choisissez un département' : 'Choose a department' ?> :
                </label>
                <select name="departement" id="departement" class="form-control" onchange="this.form.submit()">
                    <option value=""><?= $lang === 'fr' ? '-- Sélectionner un département --' : '-- Select a department --' ?></option>
                    <?php foreach ($regions[$selectedRegion] as $dept): ?>
                        <option value="<?= $dept['num'] ?>">
                            <?= $dept['name'] . '—' . $dept['num'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
          </form>
        </article>
        <?php endif; ?>


        <!-- Sélection de la ville, si on a déjà la région et le département -->
        <?php if ($selectedRegion && $selectedDept): ?>
        <article id="ville">
          <h3><?= $lang === 'fr' ? 'Renseignement de la ville' : 'City information' ?></h3>
            <p>
                <?= $lang === 'fr' ? 'Région' : 'Region' ?> : <strong><?= htmlspecialchars($selectedRegion) ?></strong>
                 
            </p>
            <p>
                    <?= $lang === 'fr' ? 'Département' : 'Department' ?> :
                  <strong> 
                    <?php
                 
                    // On afficher le nom du département
                    foreach ($regions[$selectedRegion] as $dept) {
                        if ($dept['num'] === $selectedDept) {
                        echo htmlspecialchars($dept['name'] . '—' . $dept['num']);
                        break;
                        }
                    }
                    ?>
                    </strong>
            </p>
          <form action="prevision.php?lang=<?=$lang?>" method="get">
           <input type="hidden" name="region" value="<?=$selectedRegion?>">
            <label for="ville">
              <?= $lang === 'fr' ? 'Choisissez une ville' : 'Choose a city' ?> :
            </label>
            <select name="ville" id="ville" class="form-control" required>
              <option value=""><?= $lang === 'fr' ? '-- Sélectionner une ville --' : '-- Select a city --' ?></option>
              <?php
              // liste des villes du département sélectionné
              foreach ($regions[$selectedRegion] as $dept) {
                if ($dept['num'] === $selectedDept) {
                  foreach ($dept['cities'] as $city) {
                    $nomVille = $city['name']; // Pour ne recuperer que le nom dans prevision
                    echo '<option value="' . $nomVille . '">' . htmlspecialchars($nomVille . '-' . $city['code']) . '</option>';
                  }
                  break;
                }
              }
              ?>
            </select>
            <button type="submit" class="tab-btn">
                <i class="fas fa-search"></i> <?= $lang === 'fr' ? 'Afficher les Previsions' : 'Show forecast' ?>
            </button>
          </form>
        </article>
        <?php endif; ?>

      </div>
    </div>
  </section>
</main>

<?php require "includes/footer.inc.php"; ?>
